found(html,5).
found(head,5).
found(meta,59).
found(title,10).
found(script,79).
found(link,46).
found(noscript,2).
found(body,5).
found(div,513).
found(a,587).
found(h1,8).
found(span,759).
found(img,29).
found(p,38).
found(i,175).
found(sup,5).
found(input,13).
found(h2,9).
found(label,4).
found(ul,57).
found(li,443).
found(pre,19).
found(h3,28).
found(br,2).
found(ol,1).
found(small,1).
found(style,8).
found(table,1).
found(tbody,1).
found(tr,1).
found(th,1).
found(td,1).
found(b,5).
found(hr,2).
found(esi,1).
found(nav,16).
found(form,5).
found(footer,5).
found(anonymous,1).
found(brands,1).
found(iframe,1).
found(ytd,2).
found(svg,29).
found(g,9).
found(path,24).
found(symbol,5).
found(circle,1).
found(line,4).
found(polyline,2).
found(main,3).
found(use,19).
found(aside,2).
found(header,4).
found(h4,2).
found(mask,1).
found(rect,1).
found(button,16).
